### ISSUE TITLE
Import Logging

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/darlingtonia#33] opened 2018-07-07 18:52 UTC
Every Import

Should display the following info for each record being processed:
* Source record unique identifier
    * Filename OR record number in stream OR unique ID in record # i.e. if there’s an error reported, how do I find the thing I need to go back and fix?
* Any record validation (input format) errors 
* Any work validation (model level) errors
* File(s) being attached
    * Any file-level errors (missing files, etc.)

Should display a summary of the overall import run
* Number of input records read
* Number of new objects created 
* Number of existing objects 
    * skipped (if the rule is to skip existing) OR
    * updated (if the rule is to update existing)
* Number of objects not created due to errors

Timestamps would be nice for profiling
* Start and end time for each record
    * OR (even better) start and duration for each record # this gives us important performance info

Logs should be easily machine parsable for easy integration into Splunk and other log aggregation systems.

BONUS: Configurable verbosity

**Comment by RachelDCE** [comment] 2019-02-12 16:13
Duplicate of curationexperts/tenejo#72

**Closed by RachelDCE** 2019-02-12 16:13 UTC
Labels: duplicate
