### ISSUE TITLE
Summary Logging

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/darlingtonia#38] opened 2018-12-18 21:07 UTC
**ACCEPTANCE**
Provide a summary of as many of the following stats as feasible (in the scoped time)

- [ ] Number of input records read
- [ ] Number of new objects created
- [ ] Number of objects not created due to errors

**Comment by RachelDCE** [comment] 2019-02-12 16:14
Duplicate of curationexperts/tenejo#143

**Closed by RachelDCE** 2019-02-12 16:14 UTC
Labels: duplicate
