### ISSUE TITLE
Configure Logfile

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/darlingtonia#37] opened 2018-12-18 21:02 UTC
**ACCEPTANCE**
- [ ] Allow me to configure the log location & name
- [ ] Allow me to display output on STDOUT optionally

Requires #36

**Comment by RachelDCE** [comment] 2019-02-12 16:11
Duplicate of curationexperts/tenejo#167

**Closed by RachelDCE** 2019-02-12 16:11 UTC
Labels: duplicate
